# Base configs
baseurl: ""
url: "https://tsondt.github.io/photos"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
sass:
  sass_dir: assets/css
  style: compressed
exclude: [
  "node_modules",
  "src",
  "*.sh",
  "Dockerfile",
  "Gemfile*",
  "package.json",
  "yarn.lock",
  "webpack.config.js",
  "LICENSE",
  "README.md"
]

# UI configs
title: "Photos"
subtitle: ""
author: "tsondt"
bio: ""
publicise: ""
web_design: "AJ"
social_urls:
  linkedin: "https://ca.linkedin.com/in/tsondt"
  github: "https://github.com/tsondt"
