# Base configs
baseurl: ""
url: "https://tsondt.github.io/photos"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
sass:
  sass_dir: assets/css
  style: compressed

# UI configs
title: "Photos"
subtitle: ""
author: "tsondt"
bio: ""
publicise: ""
web_design: "AJ"
social_urls:
  linkedin: "https://in.linkedin.com/in/ramswarooppatra"
  github: "https://www.github.com/ramswaroop"
